Section "Device"
	Identifier	"AMD0"
	Driver	"amdgpu"
	Option	"Accel"	"on"
	Option	"DRI"	"3"
	Option	"TearFree"	"true"
	BusID	"PCI:8:0:0"
EndSection

Section "Device"
	Identifier	"AMD1"
	Driver	"amdgpu"
	Option	"Accel"	"on"
	Option	"DRI"	"3"
	Option	"TearFree"	"true"
	BusID	"PCI:9:0:0"
EndSection
