Section "Device"
	Identifier	"AMD0"
	Driver	"amdgpu"
	Option	"Accel"	"on"
	Option	"DRI"	"3"
	Option	"TearFree"	"true"
EndSection

Section "Device"
	Identifier	"AMD1"
	Driver	"amdgpu"
	Option	"Accel"	"on"
	Option	"DRI"	"3"
	Option	"TearFree"	"true"
EndSection
